apiVersion: skaffold/v3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8s/*
build:
  local:  
    push: false
  artifacts:
    - image: arkaanfast/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: arkaanfast/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '**/*.js'
            dest: .
    - image: arkaanfast/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: arkaanfast/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: arkaanfast/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: arkaanfast/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .