# Dont learn the syntax understand it !!
# So yes A deployment can monitor multiple pods !! 
# And each pod can run 1 or more containers !
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: arkaanfast/auth
          # Declare a env variable that points to our JWT_SECRET !!
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

          # imagePullPolicy: Never
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata: 
  name: auth-srv
spec:
  selector:
    # This line checks which pods have a label of app named auth!!
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000 