apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers: 
        - name: nats
          image: nats-streaming:0.17.0
          args: [
            '-p',
            '4222',
            '-m',
            '8222',
            # hb stands for heart beat
            # hbi is how often NATS-SERER will make hb request to each client
            '-hbi',
            '5s',
            # hbt is how long each client has to respond
            '-hbt',
            '5s',
            # hbf is how many times a client can fail and indicates that it is dead
            '-hbf',
            '2',
            '-SD',
            '-cid',
            'ticketing'
          ]
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222